### ISSUE TITLE
Installation failed / not working

### ISSUE THREAD

**Issue by thomasgrosser** [mschlenstedt/LoxBerry-Plugin-LoxMatic#1]
Software error:

Global symbol "$saveformdata" requires explicit package name (did you forget to declare "my $saveformdata"?) at /opt/loxberry/webfrontend/htmlauth/plugins/loxmatic/index.cgi line 72.
Global symbol "$resp" requires explicit package name (did you forget to declare "my $resp"?) at /opt/loxberry/webfrontend/htmlauth/plugins/loxmatic/index.cgi line 88.
Global symbol "$resp" requires explicit package name (did you forget to declare "my $resp"?) at /opt/loxberry/webfrontend/htmlauth/plugins/loxmatic/index.cgi line 89.
Global symbol "$resp" requires explicit package name (did you forget to declare "my $resp"?) at /opt/loxberry/webfrontend/htmlauth/plugins/loxmatic/index.cgi line 90.
Global symbol "$resp" requires explicit package name (did you forget to declare "my $resp"?) at /opt/loxberry/webfrontend/htmlauth/plugins/loxmatic/index.cgi line 91.
Global symbol "$resp" requires explicit package name (did you forget to declare "my $resp"?) at /opt/loxberry/webfrontend/htmlauth/plugins/loxmatic/index.cgi line 93.
Execution of /opt/loxberry/webfrontend/htmlauth/plugins/loxmatic/index.cgi aborted due to compilation errors.
Depending of what you have done, report this error to the plugin developer or the LoxBerry-Core team.
Further information you may find in the error logs.

**Comment by mschlenstedt** [comment]
Please try current PreRelease 0.0.1

**Comment by thomasgrosser** [comment]
Hallo,
die Installation funktioniert !!!
Der Import der names_xxx.xxx.xxx.xxx funktioniert auch !!!
Aber wie geht es dann weiter ????
LG Thomas

**Comment by mschlenstedt** [comment]
Du musst jetzt noch das MQTT Gateway Plugin installieren und einrichten. Am besten weiter im Forumsthread fragen. 

Ich werde das Wiki aber auch noch mit einer genauen Anleitung ergänzen.

**Comment by mschlenstedt** [comment]
Keine Rückmeldung mehr -> zu.
