### ISSUE TITLE
Raspberry4 mit IOBroker Image Cul-Stick/USB-Speicher ohne Funktion

### ISSUE THREAD

**Issue by mopetfahrer** [mschlenstedt/LoxBerry-Plugin-LoxMatic#12]
Hallo,
Habe einen Raspberry4 mit fertig Image von IOBrocker und RPI-RF-MOD.
Anlernen eines CUL-Stick funktioniert nicht. Andere CCU Komponenten normale Funktion.

Meldung CUxD
USB 1-1 - USB2.0 Hub [HUB] - Sun Nov 24 11:29:38 2019
  USB 1-1.3 - Ultra Fit [STORAGE] - Sun Nov 24 11:29:38 2019
  USB 1-1.4 - CUL868 [COMM] - no tty - Sun Nov 24 11:29:38 2019
  Kein TTY-Device connected!

  Erfolgreich mit HomeMatic-CCU 127.0.0.1:8183 verbunden!

  als RPC-Server(INIT) von HomeMatic-CCU (1935) angefordert!

  Diese Web-Seite wurde aufgerufen von: 192.168.183.26

  CUxD-Uptime(2.3.4):     0 Tag(e) 01:31:18, 203744 Bytes belegt, Compiled Sep 18 2019 17:32:06
  CCU-Uptime(3.47.22):    0 Tag(e) 16:01:23, load-average: 0.00 0.00 0.00, 10s-cpu-load: 2.4%
  Speicher:  Total 3999780k  Used 860440k  Free 3139340k  (Cached 445988k)  Available 3541392k
  CPU(1): ARMv7 Processor rev 3 (v7l) [108.00 bogomips]
  CPU(2): ARMv7 Processor rev 3 (v7l) [108.00 bogomips]
  CPU(3): ARMv7 Processor rev 3 (v7l) [108.00 bogomips]
  CPU(4): ARMv7 Processor rev 3 (v7l) [108.00 bogomips]
  Linux version 4.19.75-v7l+ (dom@buildbot) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1270 SMP Tue Sep 24 18:51:41 BST 2019
  aktive CCU-Prozesse: ReGaHss(1) rfd(1) hs485d(0) java(1)

sudo pivccu-info
piVCCU version: 3.47.22-32
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  RPI-RF-MOD
HMIP Hardware:  RPI-RF-MOD
Board serial:   58A9A71FFE
Radio MAC:      unknown
SGTIN:          3014F711A0001F58A9A71FFE
State:          RUNNING
PID:            15033
IP:             192.168.183.29
CPU use:        37.39 seconds
BlkIO use:      48.11 MiB
Memory use:     232.35 MiB
KMem use:       14.84 MiB
Link:           vethpivccu
 TX bytes:      2.07 MiB
 RX bytes:      2.41 MiB
 Total bytes:   4.48 MiB

sudo dpkg-reconfigure pivccu3 
Mehrfach ausgeführt, ohne Erfolg, weder Cul noch USB 

Können Sie mir helfen?
Gruß Mopetfahrer

**Comment by mschlenstedt** [comment]
Leider nein. Hier geht es um den LoxBerry, nicht um ioBroker.
