### ISSUE TITLE
keine Funktion nach update auf V2.2.

### ISSUE THREAD

**Issue by Datenkrake156** [mschlenstedt/LoxBerry-Plugin-LoxMatic#13]
Hallo,

nach dem Loxberry-update auf V.2.2.0 startet loxmatic nicht mehr. Die Fehlermeldung:
 LoxMatic Plugin benachrichtigt über folgenden FEHLER:

Cannot find the needed kernel modules. Giving up. Please update LoxBerry AND the Plugin to the latest versions.
Die Debug-Anzeige:
 INFO: LoxBerry Version 2.2.0 ( is_raspberry.cfg )
 INFO: LoxMatic Version 0.4.1
 INFO: Loglevel: 7
 INFO: Killing any running RFD instance...
 INFO: Killing any running HMSERVER instance...
 INFO: Killing any running MULTIMACD instance...
 INFO: Killing any running HM2MQTT instance...
 INFO: We are in long mode. Hardware will be initialized.
 INFO: Identifying Homematic Hardware...
 ERROR: Cannot find the needed kernel modules. Giving up.

Ich hoffe, dies hilft zur Fehlersuche. Alle Bewegungsmelder funktionieren jetzt nicht mehr!

Schöne Grüße

Armin

**Comment by mschlenstedt** [comment]
Für V2.2 brauchst Du auch ein Update des Loxmatic Plugins. Das ist geradirbeit und wird zum Release von V2.2 fertig sein (aktuell ist das ein PreRelease!).

**Comment by mschlenstedt** [comment]
Bitte Version 0.4.2 installieren: https://github.com/mschlenstedt/LoxBerry-Plugin-LoxMatic/archive/LoxMatic-0.4.2.zip

**Comment by Datenkrake156** [comment]
Hallo Michael,

vielen Dank für die schnelle Reaktion! War mein Fehler; keine Ahnung, ob Pre-Release noch aus der Zeit der Installation eingestellt war  oder ob ich  irgendwann zufällig darauf gekommen bin. Ist jetzt jedenfalls umgestellt.

Die App läuft, alle drei Dienste stellten sich wieder auf Grün, aber: die Geräte schalteten nicht! Nach diversen Suchereien bin ich mittels HM-Manager dahinter gekommen, daß keins der Geräte mehr in der Platine RPI-RF-MOD angemeldet war. Über Werksrest darf ich alle 30 Geräte (Bewegungsmelder, Fenstergriffe, Thermostate usw.) neu anmelden. Extra Konditionstraining ist also mehr nötig, denn bis zum Abschluß bin ich etlichemale die Treppen im Haus rauf und runter gelaufen :-(( ....

Ich hoffe, daß nur ich mal wieder der Pechvogel bin.

Alles Gute und bleibt gesund

Armin
