### ISSUE TITLE
RFD not running, HMServer not running - Firmwareupdate of your Homematic Module RPI-RF-MOD was initialized

### ISSUE THREAD

**Issue by auditor29** [mschlenstedt/LoxBerry-Plugin-LoxMatic#17]
Hallo Michael,

ich bitte einmal um Hilfe, da ich einfach nicht mehr weiter komme.
Habe auf meinem Loxberry (Version 2.2.1.2) das PlugIn LoxMatic (V.0.4.2) installiert. Als Hardware kommt ein Pi 3 mit dem RPI-RF-MOD zum Einsatz. Nach der Installation kam folgende Meldung im PlugIn und per E-Mail:

08.01.2022 22:22: Firmwareupdate of your Homematic Module RPI-RF-MOD was initialized.

Seither tut sich nichts mehr. Das PlugIn meldet:

RFD not running | HMServer not running | HM2MQTT running (PID 9282)

Im Debug finde ich überall ein Error mit dem Hinweis: "HM environment was not started successfully"

Wo könnte ich mit der Fehlersuche beginnen? 

Vielen Dank für Deine Unterstützung!

**Comment by Loxfreek** [comment]
Ich habe genau die gleiche Konfiguration im Einsatz und läuft ohne Probleme. Ein paar Gedanken um den Fehler einzugrenzen:
1. War das System jemals im stabilen Betrieb oder ist es erstmalig aufgesetzt? Wenn erstmalig, dann würde ich das System noch einmal komplett neu aufsetzen. 
2. Bis du sicher, dass das HM-Modul richtig montiert ist? War das Modul neu?
3. Hast du ggf. bei der Installation des Plugin zu früh abgebrochen?
2. Nur zum Test: Meine Historie ist so gelaufen, dass ich ursprünglich über die Loxberry Version 1.4.2 auf die 2.0.x und dann auf die 2.2.1.2 gegangen bin. Das Modul HM Module ist dabei immer gelaufen. Evtl. gehst du ja auch beim Loxberry setup mal eine Version zurück.

Vielleicht sind meine Tipps zu einfach und Michael hat ja auch wesentlich mehr Expertise
Viel Erfolg.

**Comment by mschlenstedt** [comment]
Ohne Logfiles kann ich nichts machen. Stell das Logging auf "Debug" und hänge das vollständige Daemon-Logfile hier an. Und das Logfile von der Installation.

**Comment by auditor29** [comment]
> Ich habe genau die gleiche Konfiguration im Einsatz und läuft ohne Probleme. Ein paar Gedanken um den Fehler einzugrenzen:
> 
>     1. War das System jemals im stabilen Betrieb oder ist es erstmalig aufgesetzt? Wenn erstmalig, dann würde ich das System noch einmal komplett neu aufsetzen.
> 
>     2. Bis du sicher, dass das HM-Modul richtig montiert ist? War das Modul neu?
> 
>     3. Hast du ggf. bei der Installation des Plugin zu früh abgebrochen?
> 
>     4. Nur zum Test: Meine Historie ist so gelaufen, dass ich ursprünglich über die Loxberry Version 1.4.2 auf die 2.0.x und dann auf die 2.2.1.2 gegangen bin. Das Modul HM Module ist dabei immer gelaufen. Evtl. gehst du ja auch beim Loxberry setup mal eine Version zurück.
> 
> 
> Vielleicht sind meine Tipps zu einfach und Michael hat ja auch wesentlich mehr Expertise Viel Erfolg.

Hallo Loxfreek,

vielen Dank für Deine schnelle Hilfe und für die Tipps! Michael hat sich auch schon gemeldet.
Zu Deinen Ideen:
1. Das System läuft schon sehr lange. Mindestens drei Jahre. Genau kann ich es nicht mehr ermitteln.
2.  Ja, das Modul ist ganz neu von ELV und scheint auch richtig montiert zu sein. Im Logfile steht: 
<INFO> We found a RTC RX8130. This must be a RPI-RF-MOD Module.
3. Das Log der Installation endet mit den Zeilen: 
08.01.2022 21:19:07 <OK> All Plugin files were installed successfully and system was cleaned up.
08.01.2022 21:19:07 <INFO> Saving logfile. 
Scheint also funktioniert zu haben.
4. Argh! Das möchte ich gerne vermeiden. Ich nutze mehrere Plug-Ins, die alle super laufen. Da würde ich nur recht ungern einen so tiefen Eingriff ins System vornehmen.

Loxfreek, vielen Dank nochmal für Deine Hilfe! habe mich über Deine Tipps sehr gefreut!

**Comment by auditor29** [comment]
> Ohne Logfiles kann ich nichts machen. Stell das Logging auf "Debug" und hänge das vollständige Daemon-Logfile hier an. Und das Logfile von der Installation.

Hallo Michael,

da hätte ich auch selber drauf kommen können. Sorry!
Hier die Files:
[loxmatic.log](https://github.com/mschlenstedt/LoxBerry-Plugin-LoxMatic/files/7863969/loxmatic.log)
[20220113_160654_588_Daemon.log](https://github.com/mschlenstedt/LoxBerry-Plugin-LoxMatic/files/7863970/20220113_160654_588_Daemon.log)
Loxfreek war so freundlich und hat schon ein paar Tipps gegeben. Ich habe den Loxberry nochmals ausgeschaltet und die neue Platine überprüft. Daher sind die Logfiles von heute. Das System hängt jedoch seit der Erstinbetriebnahme mit dem RPI-RF-MOD Module in diesem Zustand seit dem 8.1. um 22:22 Uhr. 

Vielen Dank für Deine Hilfe!

**Comment by mschlenstedt** [comment]
Er kann mit dem Modul nicht kommunizieren. Hast Du an der seriellen Konsole oder sonstwie an der seriellen Schnittstelle oder Bluetooth mal was gemacht?

Am Besten mal einen ganz frischen LoxBerrx auf einer separaten SD-Karte aufsetzen, auf den letzten Stand bringen und dann nur das LoxMatic Plugin installieren. Wenn es dann geht weißt Du schon einmal, dass das Modul an sich iO ist.

**Comment by auditor29** [comment]
Hallo Michael,

da sagst Du was. Ich hatte einmal das FHEM PlugIn von einem gewissenen Michael Schlenstedt (vielleicht kennst Du den ja - sehr netter und hilfbereiter Zeitgenosse) installiert und mit dem EnoceanPi gearbeitet. Da habe ich einiges an der Schnittstelle verändert. Vielleicht ist das jetzt einmal ein guter Zeitpunkt den Loxberry neu aufzusetzen. Der läuft schon recht lange. Ich mache das mal in den nächsten Tagen und gebe eine Rückmeldung.
Vielen Dank für Deine Hilfe!

Viele Grüße
Thilo

**Comment by auditor29** [comment]
Hallo Michael,

habe gerade einmal einen neuen Loxberry aufgesetzt. Damit hat es auf Anhieb funktioniert.
Vielen Dank für die schnelle und professionelle Hilfe!

Viele Grüße
Thilo

@Loxfreek : schönen Dank auch für Deine Hilfe!
