### ISSUE TITLE
I2C muss über die Plugininstallation aktiviert werden

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/LoxBerry-Plugin-LoxMatic#5]
Siehe Raspi-Config. Zudem Notify, wenn es deaktiviert wird.

**Comment by Datenkrake156** [comment]
Hallo Michael,

hatte in den letzten Tag mal wieder Zeit, mich etwas mit dem Thema zu beschäftigen. Habe die App nochmals de- und neuinstalliert. Vom Gefühl her dauerte die Installationsroutine diesmal wesentlich länger und auch das Installationsprotokoll ist wesentlich umfangreicher. Jetzt wurde wohl auch die Hardware RPI-RF-MOD richtig erkannt, dies hatte ich damals im Protokoll nicht gefunden. Während der Routine wurde folgende E-Mail gesendet:  "LoxMatic Plugin benachrichtigt über folgenden FEHLER:
Cannot find the needed kernel modules. Giving up. Please update LoxBerry AND the Plugin to the latest versions."

Das Ergebnis ist leider wieder identisch: MQTT läuft (laut dieser App werden auch Daten ausgetauscht), RPI und HM nicht. Anbei sende ich mal das Fehlerlog, wonach er irgendwas nicht finden oder adressieren kann, vielleicht hilft Dir das bei der Fehlereingrenzung. Freue mich jedenfals auf die Version 0.2 oder vielleicht sogar schon 1.0?  Danke für Eure Bemühungen

Viele Grüße
Armin
['20190427_152041_728_Daemon.log'](https://github.com/mschlenstedt/LoxBerry-Plugin-LoxMatic/files/3125229/20190427_152041_728_Daemon.log)
