### ISSUE TITLE
RFD und HMServer not running

### ISSUE THREAD

**Issue by Datenkrake156** [mschlenstedt/LoxBerry-Plugin-LoxMatic#6]
Hallo Michael,
vielen Dank für diese neue Entwicklung, eröffnet viele neue Möglichkeiten, den Miniserver zu erweitern.
Bei der Installation habe ich mich an Deine Anleitung gehalten. Im Einsatz ist das Funkmodul RPI-RF-MOD. 
Das MQTT-Plugin zeigt  "MQTT Gateway running (PID12827) |  Mosquitto running (PID388)" grün an, die Häkchen bei Data und Broker sind gesetzt. Der MQTT-Spy zeigt jede Menge Meldungen an, auf dem Reiter  hm unter topic "hm/connected" und Content "1".
Im Loxmatic-Plugin stehen die drei Schieber auf on, aber es erscheint "
RFD not running | HMServer not running | HM2MQTT running (PID 20836)
".  Ich habe verschiedenste Kombinationen der Einstellungen durchgespielt und die Apps auch de- und neuinstalliert, das Ergebnis bleibt unverändert.
In der Software Homeatic-Manager erscheint zwar die IP, vermutlich deshalb allerdings keiner der Services. Ein Gerät anlernen war deshalb nicht möglich und es gibt auch keine Datei zum Import.
Anbei debug-Logfile.
Hast Du vielleicht einen Hinweis für mich? Danke im voraus
Armin

 12.03.2019 18:45:46 TASK STARTED
 Loxmatic Daemon started.
 INFO: LoxBerry Version 1.4.0.3 ( is_raspberry.cfg )
 INFO: LoxMatic Version 0.1.0
 INFO: Loglevel: 7
 INFO: Killing any running RFD instance...
 INFO: Killing any running HMSERVER instance...
 INFO: Killing any running MULTIMACD instance...
 INFO: Killing any running HM2MQTT instance...
 INFO: We are in short mode. No hardware initialisation will be done.
 INFO: This is the HM environment:
HM_HMIP_ADDRESS=
HM_HMIP_DEV=
HM_HMIP_DEVNODE=/dev/raw-uart
HM_HMIP_SERIAL=
HM_HMIP_SGTIN=
HM_HMIP_VERSION=
HM_HMRF_ADDRESS=
HM_HMRF_DEV=
HM_HMRF_DEVNODE=/dev/raw-uart
HM_HMRF_SERIAL=
HM_HMRF_VERSION=
HM_HOME=/opt/loxberry/data/plugins/loxmatic/occu/arm-gnueabihf/packages-eQ-3
HM_HOST_GPIO_RESET=18
HM_HOST_GPIO_UART=/dev/raw-uart
HM_KERNEL=4.14.87-v7+
HM_MODE=NORMAL
 INFO: Starting MULTIMACD...
 OK: OK
 INFO: Starting RFD...
 ERROR: ERROR
 INFO: Starting HMSERVER...
 ERROR: ERROR
 INFO: Starting HM2MQTT...
 OK: OK
 INFO: BidCos-RF: None
 INFO: HmIP: None
 INFO: Multimacd: 382
 INFO: RFD: None
 INFO: HMIPServer: None
 INFO: HM2MQTT: 2260
 Exit.
 12.03.2019 18:51:30 TASK FINISHED

**Comment by mschlenstedt** [comment]
Es gibt vermutlich noch einen Bug.

Logge Dich bitte mal per Putty ein, wechsle zu root und starte "raspi-config". Anschließend auf "Interfacing Options" und "I2C" aktivieren und neu starten.

**Comment by Datenkrake156** [comment]
Hallo Michael,
danke für die schnelle Antwort. Ich habe Eure Hinweise zu Putty mal überflogen, aber man muß seine Grenzen kennen. Ich bin zwar technisch interessiert, komme von der Ausbildung her aber aus der kaufmännischen Ecke. In den fast vierzig Jahren seit dem Studium bin ich privat wie dienstlich mit DOSen und Fenstern groß geworden. Linux war nie mein Thema (auch wenn ich jetzt am Wochenende auf dem CLT bei der Standbetreuung für WPIA helfe).
Es ist ja nicht so dringend für mich, da warte ich halt auf Dein nächstes Update.
Vielen Dank und macht weiter so.
Armin

**Comment by mschlenstedt** [comment]
Identisch mit #5
