### ISSUE TITLE
Nach LBUpdate 1.4.1 ging Plugin nicht mehr 

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-LoxMatic#8]
https://www.loxforum.com/forum/projektforen/loxberry/plugins/124452-plugin-homematic-auf-dem-loxberry?p=199133#post199133

Wenn das so ist, müsste man das irgendwie abfangen

**Comment by mschlenstedt** [comment]
Ich vermute das liegt am Kernel Update. Ich muss die Kernel Module über den Daemon zurückinstallieren, wenn sie nicht mehr existieren.
